from ecology_bot.admin.admin.models.awesome_data import AwesomeDataModelView
from ecology_bot.admin.admin.models.district import DistrictModelView
from ecology_bot.admin.admin.models.eco_activity import EcoActivityModelView
from ecology_bot.admin.admin.models.event import EventModelView
from ecology_bot.admin.admin.models.organization import OrganizationModelView
from ecology_bot.admin.admin.models.profile import ProfileModelView
from ecology_bot.admin.admin.models.region import RegionModelView
from ecology_bot.admin.admin.models.text_chunk import TextChunkModelView
from ecology_bot.admin.admin.models.user import UserModelView
from ecology_bot.admin.admin.models.volunteer_type import VolunteerTypeModelView
