"""empty message

Revision ID: 015089f93c19
Revises: 68bdbf779a90
Create Date: 2022-10-12 20:59:57.954798

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "015089f93c19"
down_revision = "68bdbf779a90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_global_event_id"), "global_event", ["id"], unique=False)
    op.create_index(
        op.f("ix_global_event_name"), "global_event", ["name"], unique=False
    )
    op.create_table(
        "global_event_user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("global_event_id", sa.BigInteger(), nullable=False),
        sa.Column("is_subscribed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["global_event_id"],
            ["global_event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_global_event_user_global_event_id"),
        "global_event_user",
        ["global_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_global_event_user_id"), "global_event_user", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_global_event_user_is_subscribed"),
        "global_event_user",
        ["is_subscribed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_global_event_user_user_id"),
        "global_event_user",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_global_event_user_user_id"), table_name="global_event_user")
    op.drop_index(
        op.f("ix_global_event_user_is_subscribed"), table_name="global_event_user"
    )
    op.drop_index(op.f("ix_global_event_user_id"), table_name="global_event_user")
    op.drop_index(
        op.f("ix_global_event_user_global_event_id"), table_name="global_event_user"
    )
    op.drop_table("global_event_user")
    op.drop_index(op.f("ix_global_event_name"), table_name="global_event")
    op.drop_index(op.f("ix_global_event_id"), table_name="global_event")
    op.drop_table("global_event")
    # ### end Alembic commands ###
