"""empty message

Revision ID: 0fc6c4105340
Revises: 582ca935d161
Create Date: 2022-08-19 08:16:06.591688

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0fc6c4105340'
down_revision = '582ca935d161'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('district', 'region_id',
               existing_type=sa.BigInteger(),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
