"""empty message

Revision ID: 8abeadfe1c9b
Revises: 0fc6c4105340
Create Date: 2022-08-22 18:36:54.408753

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "8abeadfe1c9b"
down_revision = "0fc6c4105340"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "activity_event_event_id_fkey", "activity_event", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "activity_event", "event", ["event_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "activity_organization_organization_id_fkey",
        "activity_organization",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "activity_organization",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "volunteer_type_event_event_id_fkey", "volunteer_type_event", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "volunteer_type_event", "event", ["event_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "volunteer_type_event", type_="foreignkey")
    op.create_foreign_key(
        "volunteer_type_event_event_id_fkey",
        "volunteer_type_event",
        "event",
        ["event_id"],
        ["id"],
    )
    op.drop_constraint(None, "activity_organization", type_="foreignkey")
    op.create_foreign_key(
        "activity_organization_organization_id_fkey",
        "activity_organization",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.drop_constraint(None, "activity_event", type_="foreignkey")
    op.create_foreign_key(
        "activity_event_event_id_fkey", "activity_event", "event", ["event_id"], ["id"]
    )
    # ### end Alembic commands ###
