"""empty message

Revision ID: cd96b9c5b277
Revises: 8abeadfe1c9b
Create Date: 2022-09-12 08:40:07.923464

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'cd96b9c5b277'
down_revision = '8abeadfe1c9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'text_chunk',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('description', sa.String(length=512), nullable=False),
        sa.Column('key', sa.String(length=64), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('weight', sa.Integer(), nullable=False, default=0, server_default=sa.text('0')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key', 'weight', name='_key_weight_uc'),
    )
    op.create_index(op.f('ix_text_chunk_id'), 'text_chunk', ['id'], unique=False)
    op.alter_column('district', 'region_id',
                    existing_type=sa.BIGINT(),
                    nullable=False)
    op.alter_column('event', 'type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('district', 'region_id',
                    existing_type=sa.BIGINT(),
                    nullable=True)
    op.drop_index(op.f('ix_text_chunk_id'), table_name='text_chunk')
    op.drop_table('text_chunk')
    # ### end Alembic commands ###
